# Generated by Django 5.0.4 on 2024-04-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('OCCUPIED', 'Occupied'), ('VACANT', 'Vacant')], default='VACANT', max_length=10)),
                ('expiration', models.DateTimeField()),
            ],
        ),
    ]
