# Generated by Django 5.0.4 on 2024-04-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_slot', '0002_alter_parkingslot_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingslot',
            name='expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
