# Generated by Django 5.0.4 on 2024-04-24 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_slot', '0003_alter_parkingslot_expiration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingslot',
            old_name='slot_id',
            new_name='id',
        ),
    ]
