# Generated by Django 5.0.4 on 2024-04-18 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking_slot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingMeter',
            fields=[
                ('meter_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('FUNCTIONAL', 'Functional'), ('NON_FUNCTIONAL', 'Non Functional')], default='FUNCTIONAL', max_length=20)),
                ('battery_level', models.IntegerField()),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parking_slot.parkingslot')),
            ],
        ),
    ]
