# Generated by Django 5.0.4 on 2024-04-24 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_meter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingmeter',
            old_name='meter_id',
            new_name='id',
        ),
    ]
